### ISSUE TITLE
Add p1 / DSMR support

### ISSUE THREAD

**Issue by ruudboon** [coolchip/node-red-contrib-smartmeter#10]
Hi,

Would it be possible to add DSMR (Dutch Smart Meter Requirements) support?
Some protocol info (hopefully you can translate it using chome :D):
http://domoticx.com/p1-poort-slimme-meter-hardware/
http://domoticx.com/arduino-p1-poort-telegrammen-uitlezen

Upd: Found official protocol: https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf

**Comment by ruudboon** [comment]
Maybe this could also be helpful.
https://github.com/ruudverheijden/node-p1-reader/blob/master/lib/parsePacket.js

https://github.com/ruudverheijden/node-p1-reader

**Comment by coolchip** [comment]
Hello. This node is based on the smartmeter-obis module. You have to ask the mentainer of this module to add sopport for DSMR. Than this node as the ability to do it.
