### ISSUE TITLE
Connecting to Serial -> Ethernet Converters

### ISSUE THREAD

**Issue by mode2k** [coolchip/node-red-contrib-smartmeter#12]
Hi,
i have a SML Meter connected to a serial -> ethernet converter. Is there a possiblity to connect to this?

For simulating a serial -> ethernet you can use
 ./remserial -p 22000 -s "9600 raw" /dev/ttyUSB_1
on a computer physicaly connected to the smartmeter on /dev/ttyUSB_1. The data is available on TCP 22000.

BR

mode

**Comment by mode2k** [comment]
The used smartmeter obis lib supports tcp client. See https://github.com/Apollon77/smartmeter-obis/blob/master/lib/transports/TCPTransport.js

Things to do:
Extend transport configuration by item TCPTransport
Add new configuration objects:
transportTcpHost
transportTcpPort
transportTcpMaxBufferSize
transportTcpMessageTimeout
an pass them to the options object.

**Comment by mode2k** [comment]
See my pull request: https://github.com/coolchip/node-red-contrib-smartmeter/pull/14

**Comment by coolchip** [comment]
I've merged pull request.
