### ISSUE TITLE
HTTP Host and Port field not maching

### ISSUE THREAD

**Issue by mode2k** [coolchip/node-red-contrib-smartmeter#13]
In smartmeter-connection.html the fields for HTTP Connection are named httphost and httpport
In smartmeter-connection.js the are named hostname and hostport.

**Comment by coolchip** [comment]
Thank you for reporting this issue. Please check if this PR is right:
https://github.com/coolchip/node-red-contrib-smartmeter/pull/15

**Comment by coolchip** [comment]
Should be fixed in current release
