### ISSUE TITLE
OMS Protocol

### ISSUE THREAD

**Issue by martinschki** [coolchip/node-red-contrib-smartmeter#2]
Hello!
Would it be possible to also read meters with OMS protocol? (https://en.wikipedia.org/wiki/Open_metering_system)
Specifically OMS 3.0.1 Standard Mode 5 with AES encryption

that would be perfect!!!!

**Comment by coolchip** [comment]
Hey, thank you for asking. I only wrote a wrapper for node red. The smartmeter library I used is this:
https://github.com/Apollon77/smartmeter-obis
So you have to ask @Apollon77 for implementing this protocol. If he is able to do this I can bind this to my node red wrapper.

**Comment by Apollon77** [comment]
he did: https://github.com/Apollon77/smartmeter-obis/issues/4. We will see

**Comment by coolchip** [comment]
Fine. 😉
