### ISSUE TITLE
Using smartmeter-node with EFR Smart Grid Hub

### ISSUE THREAD

**Issue by usauerbrey** [coolchip/node-red-contrib-smartmeter#21]
The EFR delivers JSON, but you have to request it with:
http://192.168.xxx.yyy/json.txt?LogName=name&LogPSWD=pwd

How can this be done? How to configure the node?

Thanks for your help
Uwe

**Comment by coolchip** [comment]
The node supports the "JsonEfrProtocol". You just have to choose this protocoll. Then use "HttpRequestTransport" as Transport and add your IP 192.... as Host source.
