### ISSUE TITLE
Holley DTZ541 interpretation der Phasenwinkel

### ISSUE THREAD

**Issue by Jemeins** [coolchip/node-red-contrib-smartmeter#24]
Moin,
wie sind unten genannten Phasenwinkel zu interpretieren?
1-0:81.7.4*255 -> Phasenwinkel I L1 zu U L1 -> 324°
1-0:81.7.15*255 -> Phasenwinkel I L2 zu U L2 -> 306°
1-0:81.7.26*255 -> Phasenwinkel I L3 zu U L3 -> 306°

Mein Ansatz mit den gemessenen Werten:
Phasenwinkel I L1 zu U L1 -> 324° = -36°
Phasenwinkel I L2 zu U L2 -> 306° = -54°
Phasenwinkel I L3 zu U L3 -> 306° = -54°

Die Phasenverschiebungen kommen mir allerdings arg hoch vor.

**Comment by coolchip** [comment]
Danke für die Frage. Dieser Node-RED Node basiert auf dem Modul https://github.com/Apollon77/smartmeter-obis. Hier steckt die ganze Logik für das Auslesen und evtl. umrechnen. Mein Node reicht diese Werte nur durch. Ich kann deswegen leider nichts dazu sagen. Sprechen Sie doch mal mit Apollon. Vielleicht haben Sie auch einen Fehler gefunden, der behoben werden kann.
