### ISSUE TITLE
Engelmann SensoStar U meter support?

### ISSUE THREAD

**Issue by FreeTechNick** [coolchip/node-red-contrib-smartmeter#26]
Hi,
my "district heating provider" has replaced the current meter with an Engelmann SensoStar U. Unfortunately, I can not manage to read the data from the meter. Is this supported or does anyone have experience with it? Thank you.

Regards Markus

**Comment by coolchip** [comment]
Hello. This node is based on the smartmeter-obis module. You have to ask the mentainer of this module to add support for this. Than my node has the ability to do it.

You can find the source here: https://github.com/Apollon77/smartmeter-obis

If smartmeter-obis is supporting it but you miss an configuration parameter, come back to me. ;-)

**Comment by coolchip** [comment]
If I can do anything else, please ask.
