### ISSUE TITLE
Not working on Raspi in container (Home Assistant Addon) anymore, node-serialport upstream bug

### ISSUE THREAD

**Issue by KlausHans** [coolchip/node-red-contrib-smartmeter#40]
Hello, after updating, node red isn't working any more for me. If i start with all flows disabled it works. With only the smartmeter node enabled it stops working.
I think it is because of the new version of node-serialport (https://github.com/coolchip/node-red-contrib-smartmeter/commit/bb63ab6fe8051ca3b56c7903d8af3a90f2584cff)

I downgraded to 0.5.3 and everything is ok again.

I am using Home Assistant with the node red addon. For downgrade i added
```
npm_packages:
  - node-red-contrib-smartmeter@0.5.3
```
in the config. Maybe this helps someone.

see 
https://github.com/hassio-addons/addon-node-red/issues/1312
https://github.com/serialport/node-serialport/issues/2438

**Comment by coolchip** [comment]
Oh man... that is ugly. I reverted the upgrade of the serialport and smartmeter-obis package. This should fix your issue. Feel free to reopen it, when you still have trouble.
