### ISSUE TITLE
node does not show up

### ISSUE THREAD

**Issue by rollercontainer** [coolchip/node-red-contrib-smartmeter#5]
Hi, 
I installed your package and it shows up in the "manage palette", but the nodes in the left menu aren't there. What went wrong?
node-red was ofc restarted.

**Comment by rollercontainer** [comment]
Node-RED version: v0.17.5

**Comment by rollercontainer** [comment]
ok, a verbose start told me:
[smartmeter] Error: Could not locate the bindings file. Tried:

**Comment by coolchip** [comment]
Oh, that's very old. I searched for it and found this:
https://github.com/node-red/node-red-nodes/issues/354
So, do you use NPM version 3.x or higher?
Have you tried to npm remove and npm install my node?

**Comment by coolchip** [comment]
@rollercontainer did that help you?

**Comment by rollercontainer** [comment]
Hm, no. I've a second RPI3B+ with fresh stretch, node-red v0.18.7, node-js v8.11.3, npm 6.2.0 with same result. I installed all globaly and it looks like even serialport is not installed correctly. Will dig further on that route.
