### ISSUE TITLE
Internal error message prompting

### ISSUE THREAD

**Issue by P1Rebo** [coolchip/node-red-contrib-smartmeter#7]
Using the nodes I get the following error within log.
"smartmeter-obis error: Error: Error on Baudrate changeover: Error: Port is not open".
The error is sent every request (tried several intervals).

Anyhow, an error should not be sent as internal (without node reference, instead encapsuled in the outer node).

**Comment by coolchip** [comment]
Thanks for your advice. I'm afraid I'm not coming to troubleshoot at the moment. 
Perhaps you can ask @Apollon77 from https://github.com/Apollon77/smartmeter-obis. I use his module.
