### ISSUE TITLE
Error while parsing SML message: Error: Wrong TL-Field 0x65 for Choice!

### ISSUE THREAD

**Issue by bluesky81** [coolchip/node-red-contrib-smartmeter#8]
Hello!
I get the Error Wrong TL-Field 0x65.

For me the message looks good.
Could you please verify:

1b1b1b1b010101017604000001620062007265000001017601010700000052fcd90b0a01484c59020002015a0101630d990076040000026200620072650000070177010b0a01484c59020002015a01017777070100603201010101010104484c590177070100600100ff010101010b0a01484c59020002015a0177070100010800ff65001ca904650052fcd9621e52ff65002f213c0177070100020800ff65001ca904650052fcd9621e52ff65000dd4b70177070100000200000101010109312e30322e3030370177070100605a02010101010105413031410177070100600500ff0101010165001ca90401010163a3d200760400000362006200726500000201710163e82300001b1b1b1b1a016868

**Comment by coolchip** [comment]
So it should be fixed here also.
