### ISSUE TITLE
Power in Watt from 1-0:15.7.0*255

### ISSUE THREAD

**Issue by CarJu** [coolchip/node-red-contrib-smartmeter#9]
I have an ehz-edl from Iskra, I get the the actual meter in 1-0:1.8.0*255 so connection is right, but I do not get the actual power... it shoud be in 1-0:15.7.0*255.

Can I get it somehow?

Thank you!

**Comment by coolchip** [comment]
Hello,
thanks for your question and sorry for the late answer. This node uses the npm lib smartmeter-obis. You can find the source here: [https://github.com/Apollon77/smartmeter-obis](https://github.com/Apollon77/smartmeter-obis)

So if there is something missing, first it has to be added to smartmeter-obis.
